# Generated by Django 4.0.6 on 2022-07-14 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='feeding date')),
                ('meal', models.CharField(choices=[('A', 'Admire'), ('D', 'Devour'), ('B', 'Bath')], default='A', max_length=1)),
                ('trash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trash')),
            ],
        ),
    ]
