# Generated by Django 4.0.6 on 2022-07-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_feeding_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='feeding',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='feeding',
            name='meal',
            field=models.CharField(choices=[('A', 'Admire'), ('D', 'Devour'), ('B', 'Bathe')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='trash',
            name='location',
            field=models.ManyToManyField(to='main_app.location'),
        ),
    ]
