# Generated by Django 4.0.6 on 2022-07-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_location_alter_feeding_options_alter_feeding_meal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(choices=[('N', 'None'), ('S', 'Smashing'), ('C', 'Cutting'), ('T', 'Tricking'), ('M', 'Moving'), ('E', 'Eating')], default='N', max_length=1)),
                ('rating', models.CharField(choices=[('N', 'None'), ('E', 'Effective'), ('M', 'Mediocre'), ('P', 'Poor')], default='N', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='trash',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='trash',
            name='uses',
            field=models.ManyToManyField(to='main_app.use'),
        ),
    ]
