# Generated by Django 4.0.6 on 2022-07-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_use_remove_trash_location_delete_location_trash_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='use',
            name='rating',
            field=models.CharField(choices=[('N', 'None'), ('E', 'Effective'), ('M', 'Mediocre'), ('P', 'Poor')], default='N', max_length=50),
        ),
        migrations.AlterField(
            model_name='use',
            name='use',
            field=models.CharField(choices=[('N', 'None'), ('S', 'Smashing'), ('C', 'Cutting'), ('T', 'Tricking'), ('M', 'Moving'), ('E', 'Eating')], default='N', max_length=50),
        ),
    ]
